version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - E:\DockerData\MySql:/var/lib/mysql
    networks:
      - dev-network

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge