version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - dev-network

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge